version: '3.1'
services:
  mongo_db:
    image: mongo:latest
    container_name: MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: readingdb
    ports:
      - '27017:27017'

networks:
  project-net:
    driver: bridge

volumes:
  mongo-db-vol:
